<a href="https://colab.research.google.com/github/Suhailarifhussain/NED-PGD-Batch4-Python-/blob/main/final_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

In [ ]:
file = pd.read_excel(r"path/name.xlsx")
Code = file.iloc[0,1]
Employee = file.iloc[0,6]
df = file[~file.iloc[:,0].isna()]
df1 = df.iloc[:, [0,5,9,14,16,21]]
df1.columns = df1.iloc[1,:]

df1 = df1[df1['Client ']!='Code:']
df1 = df1[df1['Client ']!="Client "]

df1 = df1.fillna(0)
df1.reset_index(drop=True, inplace=True)

#del df1['index']

column_to_check = df1.iloc[:, 0]


condition = ~column_to_check.astype(str).str.contains(r'Printed On', case=False, na=False)
condition_2 = ~column_to_check.astype(str).str.contains(r"Timesheet for the period", case=False, na=False)


df1 = df1[condition]
df1 = df1[condition_2]

df1 = df1[df1['Hours']!=float]
df1['Hours'].astype(float)


df1 = df1[df1['Client ']!="Total For Chargeable Time"]


ab = pd.DataFrame(columns=['Name', 'Date', 'Client_name', 'Client_code', 'Service', 'Job', 'Task', 'Analysis', 'Hours', 'Description'])


date = None
for i in range(len(df1)):
    x = df1.iloc[i,:]
    if (type(x.iloc[0]) == datetime):
        date = x.iloc[0]
        dt_object = datetime.strptime(str(date), '%Y-%m-%d %H:%M:%S')
        date = dt_object.strftime('%Y-%m-%d')
    elif x.iloc[-1]==0:
        ab.loc[i-1,"Client_name"] = x.iloc[0]
        ab.loc[i-1,"Description"] = x.iloc[2]
    else:
        ab.loc[i,"Name"] = Employee
        ab.loc[i, 'Date'] = date
        ab.loc[i, "Client_code"] = x.iloc[0]
        ab.loc[i,"Service"] = x.iloc[1]
        ab.loc[i, "Job"] = x.iloc[2]
        ab.loc[i, "Task"] = x.iloc[3]
        ab.loc[i, "Analysis"] = x.iloc[4]
        ab.loc[i, "Hours"] = x.iloc[5]




ab = ab[~ab['Client_name'].isna()]
ab = ab[~ab["Service"].isna()]

ab.reset_index(drop=True, inplace=True)
ab.index +=1

ab['Job/Tasks'] = ab['Job'].str.cat(ab['Task'], sep='/')
ab['Services/Analysis'] = ab['Service'].str.cat(ab['Analysis'], sep='/')
ab.drop(['Service', 'Task', 'Analysis', 'Job'], axis=1, inplace=True)


cols_order = ['Name', 'Date', 'Client_name', 'Client_code', 'Job/Tasks',
       'Services/Analysis', 'Description', 'Hours']

final_df = ab.reindex(columns=cols_order)
final_df

FileNotFoundError: ignored

In [ ]:
#ab['Hours'].sum()

80.02

In [ ]:
#final_df.to_excel(r"path/name.xlsx")

In [ ]:
final_df

,Name,Date,Client_name,Client_code,Job/Tasks,Services/Analysis,Description,Hours
1,Saqib Ali,2023-10-09,Sabden Trust,SAB002,Assurance Work/Chargeable Work,Assurance/Chargeable Time,"Materiality calculation, Updating interim Work...",0.83
2,Saqib Ali,2023-10-09,Sabden Trust,SAB002,Assurance Work/Chargeable Work,Assurance/Chargeable Time,Mapping and Sampling of income and OPEX,0.93
3,Saqib Ali,2023-10-10,Sabden Trust,SAB002,Assurance Work/Chargeable Work,Assurance/Chargeable Time,Updating debtors and creditors working papers ...,1.72
4,Saqib Ali,2023-10-10,Sabden Trust,SAB002,Assurance Work/Chargeable Work,Assurance/Chargeable Time,"Working on debtors, sampling of trade detbors,...",1.07
5,Saqib Ali,2023-10-10,Sabden Trust,SAB002,Assurance Work/Chargeable Work,Assurance/Chargeable Time,"Working on fixed assets, updating working paper",0.9
...,...,...,...,...,...,...,...,...
63,Saqib Ali,2023-10-24,Dr Challoner's Grammar School,DRC001,Assurance Work/Chargeable Work,Assurance/Chargeable Time,Working on TB mapping and OPEX Sampling,1.38
64,Saqib Ali,2023-10-24,Dr Challoner's Grammar School,DRC001,Assurance Work/Chargeable Work,Assurance/Chargeable Time,Working on TB mapping and Income Sampling,1.5
65,Saqib Ali,2023-10-24,Dr Challoner's Grammar School,DRC001,Assurance Work/Chargeable Work,Assurance/Chargeable Time,Mapping of fixed assets and sampling,0.5
66,Saqib Ali,2023-10-24,Khalsa Academies Trust Ltd,KHA001,Assurance Work/Chargeable Work,Assurance/Chargeable Time,TB Mapping and OPEX sampling,0.7
67,Saqib Ali,2023-10-24,The Western Charitable Foundation,THE015,Assurance Work/Chargeable Work,Assurance/Chargeable Time,"Working on identifying accruals, prepayments a...",1.12